name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install sqlite3
        run: sudo apt install -y sqlite3
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pipenv"
      - name: Install pipenv
        run: pip install pipenv
      - name: Sync
        run: pipenv sync --dev
      - name: Test
        run: pipenv run test
